language: node_js
sudo: false
notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
      - shawn.waldon@kitware.com
      - patrick-oleary@kitware.com
    on_success: change
    on_failure: always
cache:
  directories:
    - node_modules
    - Documentation/build-tmp
node_js:
  - "5.0.x"
script:
  - npm run build:release
  - git config --global user.name "Travis CI"
  - git config --global user.email "sebastien.jourdain@kitware.com"
  - export GIT_PUBLISH_URL=https://${GH_TOKEN}@github.com/Kitware/light-viz.git
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run doc:publish; fi
after_success:
  - npm run semantic-release
